alias fuck='eval $(thefuck $(fc -ln -1))'
alias server="python -m SimpleHTTPServer"
alias ..="cd .."
alias ....='cd ../..'
alias c="clear"
alias l="ls"
alias ll="ls -lh"
alias la="ls -a"
alias lla="ls -alh"
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias df='df -h'
alias lynx='exec '/Applications/Lynxlet.app/Contents/Resources/termlet''
alias code='cd ~/Documents/Code/'
alias code-py='cd ~/Documents/Code/Python'
alias code-java='cd ~/Documents/Code/Java'
alias code-js='cd ~/Documents/Code/JavaScript'
alias code-ios='cd ~/Documents/Code/iOS'
alias code-processing='cd ~/Documents/Code/Processing'
alias code-shell='cd ~/Documents/Code/Shell'
